## name:     Catppuccin Macchiato 🌺
## author:   Pocco81 (https://github.com/Pocco81)
## license:  MIT
## upstream: https://github.com/catppuccin/mako/blob/main/themes/catppuccin-macchiato
## blurb:    Soothing pastel theme for the high-spirited!


background-color=#24273a55 #23273a
text-color=#cad3f5
border-color=#8aadf4
progress-color=over #363a4f

[urgency=high]
border-color=#f5a97f
