# Read the user manual for documentation: http://www.musicpd.org/doc/user/
# See exaple profile in: /usr/share/doc/mpd/mpdconf.example

# MPD 扫描音乐文件夹
music_directory "$HOME/Music"
# 播放列表存储文件夹
playlist_directory "$HOME/.config/mpd/playlists"

# 音乐数据库
db_file "$HOME/.cache/mpd/database"
# MPD 运行日志
log_file "$HOME/.cache/mpd/log"
# MPD 进程ID文件
pid_file "$HOME/.local/state/mpd/pid"
# MPD 状态文件
state_file "$HOME/.local/state/mpd/state"
# 标签数据库
sticker_file "$HOME/.cache/mpd/sticker.sql"

# 关联ip地址，用于客户端可访问地址
bind_to_address "127.0.0.1"

# 启动MPD不要自动播放
restore_paused "yes"
# 自动更新音乐数据库（只支持Linux）
auto_update	"yes"

# 音乐播放驱动
audio_output {
	type "pipewire"
	name "PipeWire Sound Server"
}
