# see default settings https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/keymap-default.toml
[mgr]
prepend_keymap = [
  { on = [ "!"], run = 'shell "$SHELL" --block', desc = "Open shell here" },
  { on = "<C-u>", run = "seek -5", desc = "Seek up 5 units in the preview" },
  { on = "<C-d>", run = "seek 5", desc = "Seek down 5 units in the preview" },
  { on = "K", run = "arrow -50%", desc = "Move cursor up half page" },
  { on = "J", run = "arrow 50%", desc = "Move cursor down half page" },
  { on = "<A-k>", run = "arrow -5", desc = "Move cursor up half page" },
  { on = "<A-j>", run = "arrow 5", desc = "Move cursor down half page" },
  { on = "S", run = "search --via=fd", desc = "Search files by name using fd" },
  { on = [ "c", "y" ], run = 'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list', desc = "Copy to clipboard" },
  { on = "A", run = "create --dir", desc = "Create a dir" },
  { on = [ "g", "C" ], run = "cd ~/.cache", desc = "Go ~/.cache" },
  { on = [ "g", "D" ], run = "cd ~/Documents", desc = "Go ~/Documents" },
  { on = [ "g", "l" ], run = "cd ~/.local", desc = "Go ~/.local" },
  { on = [ "g", "r" ], run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"', desc = "Root of Git Repo" },
  { on = "H", run = "tab_switch -1 --relative", desc = "Switch to the previous tab" },
  { on = "L", run = "tab_switch 1 --relative", desc = "Switch to the next tab" },
  { on = "<", run = "tab_swap -1", desc = "Swap current tab with previous tab" },
  { on = ">", run = "tab_swap 1", desc = "Swap current tab with next tab" },
  # plugins keymap
  # plugin mount.yazi
  { on = "M", run = "plugin mount", desc = "mount" },
  # plugin project.yazi
  { on = ["P", "s"], run = "plugin projects save", desc = "Save current project" },
  { on = ["P", "l"], run = "plugin projects load", desc = "Load project" },
  { on = [ "P", "P" ], run = "plugin projects load_last", desc = "Load last project" },
  { on = [ "P", "d" ], run = "plugin projects delete", desc = "Delete project" },
  { on = [ "P", "D" ], run = "plugin projects delete_all", desc = "Delete all projects" },
  { on = [ "P", "m" ], run = "plugin projects 'merge current'", desc = "Merge current tab to other projects" },
  { on = [ "P", "M" ], run = "plugin projects 'merge all'", desc = "Merge current project to other projects" },
  # plugin compress.yazi
  { on = [ "c", "a" ], run = "plugin compress", desc = "Archive selected files" },
  { on = [ "c", "a", "p" ], run = "plugin compress -p", desc = "Archive selected files (password)" },
  { on = [ "c", "a", "h" ], run = "plugin compress -ph", desc = "Archive selected files (password+header)" },
  { on = [ "c", "a", "l" ], run = "plugin compress -l", desc = "Archive selected files (compression level)" },
  { on = [ "c", "a", "u" ], run = "plugin compress -phl", desc = "Archive selected files (password+header+level)" },

]
append_keymap = [
  { on = ["e",], run = "open", desc = "Open the selected files" },
  { on = ["E",], run = "open --interactive", desc = "Open the selected files interactively" },
]

[completion]
prepend_keymap = [
  { on = "<C-k>", run = "arrow -1", desc = "Move cursor up" },
  { on = "<C-j>", run = "arrow 1", desc = "Move cursor down" },
]
