# see default setting https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/yazi-default.toml
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio = [1, 4, 3]
sort_by = "natural"
sort_dir_first = true

[opener]
folder = [
  { run = 'hyprctl dispatch exec "[float; size 60% 60%; center 1] dolphin" "$1"', orphan = true, desc = "dolphin", for = "linux" },
  { run = '''kitty "nvim "$1""''', block = true, desc = "neovim", for = "linux" },
  { run = 'kitty --detach nvim "$@"', orphan = true, desc = "neovim (detached)", for = "linux" },
  { run = '''kitty "lazygit -p "$1""''', block = true, desc = "lazygit", for = "linux" },
  { run = 'code  "$@"', orphan = true, desc = "vscode", for = "linux" },
  { run = 'kitty "$@"', orphan = true, desc = "kitty", for = "linux" },
  { run = 'xdg-open "$@"', orphan = true, desc = "xdg-open", for = "linux" },
]

text = [
  { run = '$EDITOR "$@"', block = true, desc = "$EDITOR", for = "linux" },
  { run = 'nvim "$@"', block = true, desc = "neovim", for = "linux" },
  { run = 'kitty --detach nvim "$@"', block = true, desc = "neovim (detached)", for = "linux" },
  { run = 'code  "$@"', orphan = true, desc = "vscode", for = "linux" },
  { run = 'xdg-open "$@"', orphan = true, desc = "xdg-open", for = "linux" },
]

document = [
  { run = 'xdg-open "$@"', orphan = true, desc = "xdg-open", for = "linux" },
  { run = 'wps "$@"', orphan = true, desc = "wps", for = "linux" },
  { run = 'zathura "$@"', orphan = true, desc = "zathura", for = "linux" },
  { run = 'libreoffice "$@"', orphan = true, desc = "libreoffice", for = "linux" },
]

image = [
  { run = 'xdg-open "$@"', orphan = true, desc = "xdg-open", for = "linux" },
  { run = 'qimgv "$@"', orphan = true, desc = "qimgv", for = "linux" },
  { run = 'krita "$@"', orphan = true, desc = "krita", for = "linux" },
  { run = 'satty --filename "$@"', orphan = true, desc = "satty", for = "linux" },
]

video = [
  { run = 'xdg-open "$@"', orphan = true, desc = "xdg-open", for = "linux" },
  { run = 'mpv "$@"', orphan = true, desc = "mpv", for = "linux" },
  { run = 'vlc "$@"', orphan = true, desc = "vlc", for = "linux" },
]

audio = [
  { run = 'xdg-open "$@"', orphan = true, desc = "xdg-open", for = "linux" },
  { run = 'mpv "$@"', orphan = true, desc = "mpv", for = "linux" },
  { run = 'vlc "$@"', orphan = true, desc = "vlc", for = "linux" },
]

[open]
rules = [
  { name = "*/", use = [ "folder" ] },

  { mime = "text/*", use = [ "text" ] },
  { mime = "image/*", use = [ "image" ] },
  { mime = "video/*", use = [ "video" ] },
  { mime = "application/octet-stream", use = [ "video" ] },
  { mime = "audio/*", use = [ "audio" ] },
  { mime = "inode/x-empty", use = [ "text" ] },
  { mime = "application/json", use = [ "text" ] },

	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract", "reveal" ] },

	{ mime = "application/msword", use = [ "document", "reveal" ] },
	{ mime = "application/msexcel", use = [ "document", "reveal" ] },
	{ mime = "application/mspowerpoint", use = [ "document", "reveal" ] },
	{ mime = "application/openxmlformats-officedocument.wordprocessingml.document", use = [ "document", "reveal" ] },
	{ mime = "application/openxmlformats-officedocument.spreadsheetml.sheet", use = [ "document", "reveal" ] },
	{ mime = "application/openxmlformats-officedocument.presentationml.presentation", use = [ "document", "reveal" ] },
  { mime = "application/pdf", use = [ "document", "reveal" ] },
  { mime = "application/epub+zip", use = [ "document", "reveal" ] },
  { mime = "application/x-mobipocket-ebook", use = [ "document", "reveal" ] },

  { mime = "*", use = [ "open", "reveal" ] },
]
