server-name smartdns

# 端口绑定
bind [::]:6053

# 缓存设置
## 缓存大小 32MB
cache-size 32789
## 持久化缓存
cache-persist yes
## 缓存预获取（域名缓存超时前，自动重新查询域名IP）
prefetch-domain yes
## 启用缓存超时
serve-expired yes
## 过期缓存超时时间（单位：秒）
serve-expired-ttl 259200
## 过期缓存响应TTL（单位：秒）
serve-expired-reply-ttl 3
## 缓存预获取时间（单位：秒）
serve-expired-prefetch-time 21600
## 定期保存缓存文件
cache-checkpoint-time 86400

# 双栈IP优选（ipv4、ipv6 测速优先选择）
# dualstack-ip-selection yes
force-AAAA-SOA yes
force-qtype-SOA 65

# 日志设置
log-level info
log-num 1
audit-enable yes
audit-num 1

# CN 组域名列表
conf-file /etc/smartdns/direct-list.conf
conf-file /etc/smartdns/apple-cn.conf
conf-file /etc/smartdns/google-cn.conf

# Bootstrap DNS
server 8.8.8.8 -group google -exclude-default-group
server 8.8.4.4 -group google -exclude-default-group
server 1.1.1.1 -group cloudflare -exclude-default-group
server 1.0.0.1 -group cloudflare -exclude-default-group
server 9.9.9.9 -group quad9 -exclude-default-group
server 208.67.222.222 -group opendns -exclude-default-group
server 223.6.6.6 -group alidns -exclude-default-group
server 223.5.5.5 -group alidns -exclude-default-group
server 119.29.29.29 -group dnspod -exclude-default-group
server 119.28.28.28 -group dnspod -exclude-default-group
server 101.101.101.101 -group twnic -exclude-default-group

# 指定上游解析 DoH 服务器
nameserver /alidns.com/alidns
nameserver /doh.pub/dnspod
nameserver /dns.google/google
nameserver /quad9.net/quad9
nameserver /opendns.com/opendns
nameserver /cloudflare-dns.com/cloudflare
nameserver /twnic.tw/twnic
nameserver /v.recipes/google

# CN 组解析服务器，用于解析国内域名
server-https https://dns.alidns.com/dns-query -group cn -exclude-default-group
server-https https://doh.pub/dns-query -group cn -exclude-default-group
server-https https://v.recipes/dns/dns.alidns.com/dns-query -group cn -exclude-default-group
server-https https://v.recipes/dns/doh.pub/dns-query -group cn -exclude-default-group

#  默认组解析服务器，用于解析未配置国内域名IP解析
server-https https://dns.google/dns-query
server-https https://dns.quad9.net/dns-query
server-https https://doh.opendns.com/dns-query
server-https https://cloudflare-dns.com/dns-query
server-https https://dns.twnic.tw/dns-query
server-https https://v.recipes/dns/dns.google/dns-query
server-https https://v.recipes/dns/cloudflare-dns.com/dns-query

conf-file /etc/smartdns/anti-ad-smartdns.conf
