# 监听53端口
server-name smartdns
bind [::]:53
bind-tcp [::]:53
tcp-idle-time 2

# 指定上游服务器解析DOH，搭配下面的nameserver避免各方打架，不参与默认解析
server 8.8.8.8 -group google -exclude-default-group
server 8.8.4.4 -group google -exclude-default-group
server 1.1.1.1 -group cloudflare -exclude-default-group
server 1.0.0.1 -group cloudflare -exclude-default-group
server 9.9.9.9 -group quad9 -exclude-default-group
server 208.67.222.222 -group opendns -exclude-default-group
server 223.6.6.6 -group alidns -exclude-default-group
server 223.5.5.5 -group alidns -exclude-default-group
server 119.29.29.29 -group dnspod -exclude-default-group
server 119.28.28.28 -group dnspod -exclude-default-group
server 101.101.101.101 -group twnic -exclude-default-group

# China 组服务器，用于解析中国域名列表，不参与默认解析，防止泄露
server-https https://doh.pub/dns-query -group china -exclude-default-group
server-https https://dns.alidns.com/dns-query -group china -exclude-default-group
server 114.114.114.114 -group china -exclude-default-group
server 1.2.4.8 -group china -exclude-default-group

# 默认组
server-https https://dns.google/dns-query
server-https https://dns.quad9.net/dns-query
server-https https://doh.opendns.com/dns-query
server-https https://cloudflare-dns.com/dns-query
server-https https://dns.twnic.tw/dns-query

# 指定上游解析DOH服务器
nameserver /dns.alidns.com/alidns
nameserver /doh.pub/dnspod
nameserver /dns.google/google
nameserver /quad9.net/quad9
nameserver /opendns.com/opendns
nameserver /cloudflare-dns.com/cloudflare
nameserver /twnic.tw/twnic

# cache-size为缓存条数，不写会根据系统内存情况自动设置
cache-size 32768
cache-persist yes
cache-file /tmp/smartdns.cache

# 下面为开启缓存域名预获取，并缓存3天，期间每6小时重新向所有配置的上游获取一次
prefetch-domain yes
serve-expired-prefetch-time 21600
serve-expired yes
serve-expired-ttl 259200
serve-expired-reply-ttl 3
cache-checkpoint-time 86400

# ipv4、ipv6双栈优选支持
dualstack-ip-selection yes
# DNS不返回IPV6地址，有需要再开启
# force-AAAA-SOA yes

# SmartDNS提供了两种测速模式，分别是ping和tcp。smartdns默认使用三次测速。第一次为ping，第二次为tcp的80端口，第三次为tcp的443端口
# smartdns会将最佳结果保存到缓存中
speed-check-mode ping,tcp:80,tcp:443

# 启用日志
audit-enable yes
audit-file /var/log/smartdns/smartdns-audit.log

# 引用其他配置文件
conf-file /etc/smartdns/direct-list.conf
conf-file /etc/smartdns/apple-cn.conf
conf-file /etc/smartdns/google-cn.conf
conf-file /etc/smartdns/anti-ad-smartdns.conf

