# ########### Wayland ###########
env = GDK_BACKEND, wayland,x11,*
env = ELECTRON_OZONE_PLATFORM_HINT, auto
env = QT_QPA_PLATFORM, wayland;xcb
env = _JAVA_AWT_WM_NONREPARENTING, 1

# ####### Local language ########
env = LANG, zh_CN.UTF-8
env = LC_CTYPE, zh_CN.UTF-8

# #### Default application ######
# 文本编辑器
env = EDITOR, nvim
# 命令行工具
env = TERMINAL, kitty
# 浏览器
env = BROWSER, microsoft-edge-stable
# 图形文件管理器
env = GUI_FILE_MANAGER, dolphin
# 命令行文件管理器
env = TUI_FILE_MANAGER, $TERMINAL -T yazi yazi
# 应用程序运行菜单
env = APPLIACTIOIN_LAUCHER, rofi -show drun
# 选择菜单
env = LIST_PICKER, rofi -dmenu
# emoji 选择菜单
env = EMOJI_PICKER, rofi -modi emoji -show emoji
# 截图存储位置
env = SCREENSHOT_SAVE_PATH, $HOME/Pictures/Screenshots

# ########### Themes ############
env = QT_QPA_PLATFORMTHEME, kde
env = XCURSOR_THEME, Bibata-Modern-Amber
env = XCURSOR_SIZE, 40
env = HYPRCURSOR_THEME, Bibata-Modern-Amber
env = HYPRCURSOR_SIZE, 40

# ########### Others ############
# dolphin 选择启动程序问题
env = XDG_MENU_PREFIX, plasma-
