--enable-features=WebRTCPipeWireCapturer,UseOzonePlatform
# Chormium 系列浏览器141后切换屏幕崩溃
# --disable-features=WaylandWpColorManagerV1
--ozone-platform=wayland
--enable-wayland-ime
--password-store=gnome-libsecret
