#!/usr/bin/env bash
# -----------------------------------------------------
# CUSTOMIZATION
# -----------------------------------------------------
# POSH=agnoster

# -----------------------------------------------------
# Prompt
# -----------------------------------------------------
# eval "$(oh-my-posh init bash --config /usr/share/oh-my-posh/themes/cloud-context.omp.json)"
if [[ -n $DISPLAY ]]; then
	ln -snf ~/.config/starship/bracketed-segments.toml ~/.config/starship.toml
else
	ln -snf ~/.config/starship/catppuccin-powerline.toml ~/.config/starship.toml
end

if command -v starship &> /dev/null; then
  eval "$(starship init bash)"
fi
